#!/bin/bash -e
cd "${0%/*}" || exit 1                               # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
restore0Dir
runApplication setExprFields #setFields

runApplication `getApplication`

postProcess -func mySampleDict #-latestTime

touch foam.foam
#------------------------------------------------------------------------------
